choco install 7zip -y
choco install calibre --version=4.23.0
choco install cryptomator -y
choco install f.lux -y
choco install firefox -y
choco install foxitreader -y
choco install git -y
choco install keepassxc -y
choco install microsoft-windows-terminal -y
choco install obs-studio -y
choco install powershell-core -y
choco install protonvpn -y
choco install shotcut -y
choco install signal -y
choco install slack -y
choco install steam-client -y
choco install vagrant -y
choco install vcxsrv -y
choco install virtualbox --version=6.1.26 -y
choco install vscode -y
